In [1]:
import numpy as np

In [2]:
import pandas as pd

# One Dimensional Array

In [4]:
myarray = np.arange(0,18)

In [5]:
myarray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [8]:
myarray[4:7]

array([4, 5, 6])

In [9]:
myarray[9]

9

In [12]:
myarray[5:10]=100

In [13]:
myarray

array([  0,   1,   2,   3,   4, 100, 100, 100, 100, 100,  10,  11,  12,
        13,  14,  15,  16,  17])

In [14]:
myarray

array([  0,   1,   2,   3,   4, 100, 100, 100, 100, 100,  10,  11,  12,
        13,  14,  15,  16,  17])

In [15]:
myarray[:]=99

In [16]:
myarray

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       99])

In [19]:
myarray = np.arange(0,20)

In [20]:
myarray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [21]:
myarr_cp = myarray.copy()

In [23]:
myarr_cp[3:7]=100

In [24]:
myarr_cp

array([  0,   1,   2, 100, 100, 100, 100,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [25]:
myarray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

# 2D Array

In [26]:
from numpy.random import randn

In [27]:
randn(2,3)

array([[ 0.23616406, -1.55078436,  0.57872896],
       [-1.87010529, -0.48462251,  0.75026175]])

In [31]:
np.arange(6).reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [32]:
np.array([[1,2,3],[3,6,7]])

array([[1, 2, 3],
       [3, 6, 7]])

In [38]:
myarr = np.arange(50).reshape(5,10)

In [39]:
myarr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [42]:
myarr[-1]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [45]:
myarr[4][8]

48

In [46]:
myarr[-1][8]

48

In [47]:
myarr[4,8]

48

In [48]:
myarr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [54]:
myarr[3:,1:4]

array([[31, 32, 33],
       [41, 42, 43]])

In [60]:
myarr = np.arange(30,50,0.5).reshape(5,8)

In [61]:
myarr

array([[30. , 30.5, 31. , 31.5, 32. , 32.5, 33. , 33.5],
       [34. , 34.5, 35. , 35.5, 36. , 36.5, 37. , 37.5],
       [38. , 38.5, 39. , 39.5, 40. , 40.5, 41. , 41.5],
       [42. , 42.5, 43. , 43.5, 44. , 44.5, 45. , 45.5],
       [46. , 46.5, 47. , 47.5, 48. , 48.5, 49. , 49.5]])

In [62]:
myarr[3:,1:4]

array([[42.5, 43. , 43.5],
       [46.5, 47. , 47.5]])

# conditional selection

In [63]:
arr = np.arange(50)

In [64]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [67]:
arr > 34

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [68]:
trueflase_arr = arr > 34

In [69]:
trueflase_arr

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [70]:
arr[trueflase_arr]

array([35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [71]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [72]:
arr[arr>34]

array([35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

# basic operations

In [73]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [74]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [75]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

In [76]:
arr * arr

array([   0,    1,    4,    9,   16,   25,   36,   49,   64,   81,  100,
        121,  144,  169,  196,  225,  256,  289,  324,  361,  400,  441,
        484,  529,  576,  625,  676,  729,  784,  841,  900,  961, 1024,
       1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849,
       1936, 2025, 2116, 2209, 2304, 2401])

In [80]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [81]:
arr/arr

C:\Users\Hossein\Anaconda3\envs\env18\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [84]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149])

In [85]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [86]:
(arr+100)/arr

C:\Users\Hossein\Anaconda3\envs\env18\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([         inf, 101.        ,  51.        ,  34.33333333,
        26.        ,  21.        ,  17.66666667,  15.28571429,
        13.5       ,  12.11111111,  11.        ,  10.09090909,
         9.33333333,   8.69230769,   8.14285714,   7.66666667,
         7.25      ,   6.88235294,   6.55555556,   6.26315789,
         6.        ,   5.76190476,   5.54545455,   5.34782609,
         5.16666667,   5.        ,   4.84615385,   4.7037037 ,
         4.57142857,   4.44827586,   4.33333333,   4.22580645,
         4.125     ,   4.03030303,   3.94117647,   3.85714286,
         3.77777778,   3.7027027 ,   3.63157895,   3.56410256,
         3.5       ,   3.43902439,   3.38095238,   3.3255814 ,
         3.27272727,   3.22222222,   3.17391304,   3.12765957,
         3.08333333,   3.04081633])

In [88]:
arr**3

array([     0,      1,      8,     27,     64,    125,    216,    343,
          512,    729,   1000,   1331,   1728,   2197,   2744,   3375,
         4096,   4913,   5832,   6859,   8000,   9261,  10648,  12167,
        13824,  15625,  17576,  19683,  21952,  24389,  27000,  29791,
        32768,  35937,  39304,  42875,  46656,  50653,  54872,  59319,
        64000,  68921,  74088,  79507,  85184,  91125,  97336, 103823,
       110592, 117649], dtype=int32)

# universal functions

In [89]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [90]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481,
       5.47722558, 5.56776436, 5.65685425, 5.74456265, 5.83095189,
       5.91607978, 6.        , 6.08276253, 6.164414  , 6.244998  ,
       6.32455532, 6.40312424, 6.4807407 , 6.55743852, 6.63324958,
       6.70820393, 6.78232998, 6.8556546 , 6.92820323, 7.        ])

In [91]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09,
       2.64891221e+10, 7.20048993e+10, 1.95729609e+11, 5.32048241e+11,
       1.44625706e+12, 3.93133430e+12, 1.06864746e+13, 2.90488497e+13,
       7.89629602e+13, 2.14643580e+14, 5.83461743e+14, 1.58601345e+15,
       4.31123155e+15, 1.17191424e+16, 3.18559318e+16, 8.65934004e+16,
       2.35385267e+17, 6.39843494e+17, 1.73927494e+18, 4.72783947e+18,
       1.28516001e+19, 3.49342711e+19, 9.49611942e+19, 2.58131289e+20,
       7.01673591e+20, 1.90734657e+21])

In [92]:
np.max(arr)

49

In [93]:
np.min(arr)

0

In [94]:
arr.max()

49

In [95]:
arr.min()

0

# Pandas

In [106]:
import pandas as pd

In [107]:
mylabel = 'a b c d e f g'.split()
mydata = [10, 20, 30, 40, 50, 60, 70]
nparray = np.array([10, 20, 30, 40, 50, 60, 70])
mydict ={'a':10, 'b':20, 'c':30, 'd':40, 'e':50, 'f':60, 'g':70}

In [108]:
pd.Series(mydata)

0    10
1    20
2    30
3    40
4    50
5    60
6    70
dtype: int64

In [109]:
pd.Series(nparray)

0    10
1    20
2    30
3    40
4    50
5    60
6    70
dtype: int32

In [110]:
pd.Series(nparray, mylabel)

a    10
b    20
c    30
d    40
e    50
f    60
g    70
dtype: int32

In [112]:
myser = pd.Series(mydict)

In [113]:
myser

a    10
b    20
c    30
d    40
e    50
f    60
g    70
dtype: int64

In [115]:
myser['g']

70

In [124]:
myser1 = pd.Series([23, 456,25,18],["Concordia", "McGill", "UT","UBC"])

In [125]:
myser1

Concordia     23
McGill       456
UT            25
UBC           18
dtype: int64

In [123]:
myser2 = pd.Series([34, 47,78,100],["Concordia", "McGill", "MIT","UBC"])

In [126]:
myser2

Concordia     34
McGill        47
MIT           78
UBC          100
dtype: int64

In [127]:
myser1 + myser2

Concordia     57.0
MIT            NaN
McGill       503.0
UBC          118.0
UT             NaN
dtype: float64

## Pandas DataFrame

In [151]:
np.random.seed(121)

In [152]:
df = pd.DataFrame(abs(randn(5,6)*50),"a b c d e".split(), "x y z w t s".split())

In [153]:
df

x          y          z          w          t          s
a   10.601658  14.246458  28.694910  22.015508  16.505528  59.184728
b   80.768646  18.353123   0.705965  31.482090  85.482037  66.349368
c   20.093656   9.571333  70.191298  98.438427  39.520758  36.636080
d    4.387191  25.014300  25.205722  30.370305  58.322479  41.221221
e  154.336230  58.217113  54.132580  24.289800  61.744214  92.944086

In [148]:
df['x']

a    135.342492
b     42.403849
c      9.434765
d    130.298364
e      6.742036
Name: x, dtype: float64

In [149]:
type(df)

pandas.core.frame.DataFrame

In [150]:
type(df['x'])

pandas.core.series.Series

In [154]:
df

x          y          z          w          t          s
a   10.601658  14.246458  28.694910  22.015508  16.505528  59.184728
b   80.768646  18.353123   0.705965  31.482090  85.482037  66.349368
c   20.093656   9.571333  70.191298  98.438427  39.520758  36.636080
d    4.387191  25.014300  25.205722  30.370305  58.322479  41.221221
e  154.336230  58.217113  54.132580  24.289800  61.744214  92.944086

In [157]:
df[['x','y','s']]

x          y          s
a   10.601658  14.246458  59.184728
b   80.768646  18.353123  66.349368
c   20.093656   9.571333  36.636080
d    4.387191  25.014300  41.221221
e  154.336230  58.217113  92.944086

In [158]:
df

x          y          z          w          t          s
a   10.601658  14.246458  28.694910  22.015508  16.505528  59.184728
b   80.768646  18.353123   0.705965  31.482090  85.482037  66.349368
c   20.093656   9.571333  70.191298  98.438427  39.520758  36.636080
d    4.387191  25.014300  25.205722  30.370305  58.322479  41.221221
e  154.336230  58.217113  54.132580  24.289800  61.744214  92.944086

In [159]:
df['u']=df['x']*df['y']

In [160]:
df

x          y          z          w          t          s  \
a   10.601658  14.246458  28.694910  22.015508  16.505528  59.184728   
b   80.768646  18.353123   0.705965  31.482090  85.482037  66.349368   
c   20.093656   9.571333  70.191298  98.438427  39.520758  36.636080   
d    4.387191  25.014300  25.205722  30.370305  58.322479  41.221221   
e  154.336230  58.217113  54.132580  24.289800  61.744214  92.944086   

             u  
a   151.036085  
b  1482.356942  
c   192.323080  
d   109.742513  
e  8985.009750

In [165]:
df.drop('x', axis=1, inplace=True)

In [163]:
df.drop('a')

x          y          z          w          t          s  \
b   80.768646  18.353123   0.705965  31.482090  85.482037  66.349368   
c   20.093656   9.571333  70.191298  98.438427  39.520758  36.636080   
d    4.387191  25.014300  25.205722  30.370305  58.322479  41.221221   
e  154.336230  58.217113  54.132580  24.289800  61.744214  92.944086   

             u  
b  1482.356942  
c   192.323080  
d   109.742513  
e  8985.009750

In [167]:
df

y          z          w          t          s            u
a  14.246458  28.694910  22.015508  16.505528  59.184728   151.036085
b  18.353123   0.705965  31.482090  85.482037  66.349368  1482.356942
c   9.571333  70.191298  98.438427  39.520758  36.636080   192.323080
d  25.014300  25.205722  30.370305  58.322479  41.221221   109.742513
e  58.217113  54.132580  24.289800  61.744214  92.944086  8985.009750

In [169]:
df.shape

(5, 6)

# select rows

In [172]:
df.loc['a']

y     14.246458
z     28.694910
w     22.015508
t     16.505528
s     59.184728
u    151.036085
Name: a, dtype: float64

In [174]:
df.loc['e']

y      58.217113
z      54.132580
w      24.289800
t      61.744214
s      92.944086
u    8985.009750
Name: e, dtype: float64

In [178]:
df.iloc[4]

y      58.217113
z      54.132580
w      24.289800
t      61.744214
s      92.944086
u    8985.009750
Name: e, dtype: float64

In [183]:
df.loc[['a','e'], ['z','t']]

z          t
a  28.69491  16.505528
e  54.13258  61.744214

In [184]:
df.iloc[[0,-1],[0,-1]]

y            u
a  14.246458   151.036085
e  58.217113  8985.009750

In [187]:
df>20

y      z     w      t     s     u
a  False   True  True  False  True  True
b  False  False  True   True  True  True
c  False   True  True   True  True  True
d   True   True  True   True  True  True
e   True   True  True   True  True  True

In [188]:
df[df>20]

y          z          w          t          s            u
a        NaN  28.694910  22.015508        NaN  59.184728   151.036085
b        NaN        NaN  31.482090  85.482037  66.349368  1482.356942
c        NaN  70.191298  98.438427  39.520758  36.636080   192.323080
d  25.014300  25.205722  30.370305  58.322479  41.221221   109.742513
e  58.217113  54.132580  24.289800  61.744214  92.944086  8985.009750

In [189]:
df

y          z          w          t          s            u
a  14.246458  28.694910  22.015508  16.505528  59.184728   151.036085
b  18.353123   0.705965  31.482090  85.482037  66.349368  1482.356942
c   9.571333  70.191298  98.438427  39.520758  36.636080   192.323080
d  25.014300  25.205722  30.370305  58.322479  41.221221   109.742513
e  58.217113  54.132580  24.289800  61.744214  92.944086  8985.009750

In [191]:
df['y']>20

a    False
b    False
c    False
d     True
e     True
Name: y, dtype: bool

In [192]:
df[df['y']>20]

y          z          w          t          s            u
d  25.014300  25.205722  30.370305  58.322479  41.221221   109.742513
e  58.217113  54.132580  24.289800  61.744214  92.944086  8985.009750

In [193]:
df2 = pd.read_csv('insurance_data.csv')

In [195]:
df2.head()

policyID statecode       county  eq_site_limit  hu_site_limit  \
0    119736        FL  CLAY COUNTY       498960.0      498960.00   
1    448094        FL  CLAY COUNTY      1322376.3     1322376.30   
2    206893        FL  CLAY COUNTY       190724.4      190724.40   
3    333743        FL  CLAY COUNTY            0.0       79520.76   
4    172534        FL  CLAY COUNTY            0.0      254281.50   

   fl_site_limit  fr_site_limit    tiv_2011    tiv_2012  eq_site_deductible  \
0       498960.0       498960.0   498960.00   792148.90                 0.0   
1      1322376.3      1322376.3  1322376.30  1438163.57                 0.0   
2       190724.4       190724.4   190724.40   192476.78                 0.0   
3            0.0            0.0    79520.76    86854.48                 0.0   
4            0.0       254281.5   254281.50   246144.49                 0.0   

   hu_site_deductible  fl_site_deductible  fr_site_deductible  point_latitude  \
0              9979.2                 0.0                   0       30.102261   
1                 0.0                 0.0                   0       30.063936   
2                 0.0                 0.0                   0       30.089579   
3                 0.0                 0.0                   0       30.063236   
4                 0.0                 0.0                   0       30.060614   

   point_longitude         line construction  point_granularity  
0       -81.711777  Residential      Masonry                  1  
1       -81.707664  Residential      Masonry                  3  
2       -81.700455  Residential         Wood                  1  
3       -81.707703  Residential         Wood                  3  
4       -81.702675  Residential         Wood                  1

In [199]:
df2.replace('FL', 'AB', inplace=True)

In [200]:
df2.head()

policyID statecode       county  eq_site_limit  hu_site_limit  \
0    119736        AB  CLAY COUNTY       498960.0      498960.00   
1    448094        AB  CLAY COUNTY      1322376.3     1322376.30   
2    206893        AB  CLAY COUNTY       190724.4      190724.40   
3    333743        AB  CLAY COUNTY            0.0       79520.76   
4    172534        AB  CLAY COUNTY            0.0      254281.50   

   fl_site_limit  fr_site_limit    tiv_2011    tiv_2012  eq_site_deductible  \
0       498960.0       498960.0   498960.00   792148.90                 0.0   
1      1322376.3      1322376.3  1322376.30  1438163.57                 0.0   
2       190724.4       190724.4   190724.40   192476.78                 0.0   
3            0.0            0.0    79520.76    86854.48                 0.0   
4            0.0       254281.5   254281.50   246144.49                 0.0   

   hu_site_deductible  fl_site_deductible  fr_site_deductible  point_latitude  \
0              9979.2                 0.0                   0       30.102261   
1                 0.0                 0.0                   0       30.063936   
2                 0.0                 0.0                   0       30.089579   
3                 0.0                 0.0                   0       30.063236   
4                 0.0                 0.0                   0       30.060614   

   point_longitude         line construction  point_granularity  
0       -81.711777  Residential      Masonry                  1  
1       -81.707664  Residential      Masonry                  3  
2       -81.700455  Residential         Wood                  1  
3       -81.707703  Residential         Wood                  3  
4       -81.702675  Residential         Wood                  1

In [201]:
for i, row in df2.iterrows(): 
    if df2.at[i, 'policyID'] > 440000:
        print("Hi There")

Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
Hi There
H