In [2]:
import numpy as np

In [3]:
mylist = [1,2,34,56,7]

In [4]:
myarray = np.array(mylist)

In [5]:
myarray

array([ 1,  2, 34, 56,  7])

In [6]:
matrix = [[1,2,3],[4,5,6],[5,6,7]]

In [7]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [5, 6, 7]])

In [9]:
np.arange(1,20, 0.1)

array([ 1. ,  1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,
        2.1,  2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,
        3.2,  3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,
        4.3,  4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,
        5.4,  5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,
        6.5,  6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,
        7.6,  7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,
        8.7,  8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,
        9.8,  9.9, 10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8,
       10.9, 11. , 11.1, 11.2, 11.3, 11.4, 11.5, 11.6, 11.7, 11.8, 11.9,
       12. , 12.1, 12.2, 12.3, 12.4, 12.5, 12.6, 12.7, 12.8, 12.9, 13. ,
       13.1, 13.2, 13.3, 13.4, 13.5, 13.6, 13.7, 13.8, 13.9, 14. , 14.1,
       14.2, 14.3, 14.4, 14.5, 14.6, 14.7, 14.8, 14.9, 15. , 15.1, 15.2,
       15.3, 15.4, 15.5, 15.6, 15.7, 15.8, 15.9, 16

In [12]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.random.rand(4)

array([0.41897987, 0.02533021, 0.89012947, 0.11415352])

In [15]:
np.random.rand(6,6)

array([[0.32003892, 0.0284131 , 0.91270218, 0.30219133, 0.93810788,
        0.83197088],
       [0.70754372, 0.77300295, 0.59164518, 0.67386076, 0.97315417,
        0.09331413],
       [0.43954472, 0.22236309, 0.22447752, 0.98945373, 0.2144485 ,
        0.03012774],
       [0.87948732, 0.35285667, 0.79493115, 0.39670785, 0.32545916,
        0.04820103],
       [0.28924258, 0.490413  , 0.49141367, 0.55858689, 0.87502848,
        0.79317748],
       [0.12769875, 0.24052306, 0.43377552, 0.58550339, 0.34681589,
        0.61084079]])

In [16]:
np.random.randint(1,50)

46

In [24]:
a=np.random.randint(1,100,size=30)
a

array([45, 35, 59,  8, 22, 77, 12, 87, 79, 56, 97, 27, 44, 99, 69, 93, 99,
       99, 70, 28, 60, 19, 69, 48, 90, 19, 86, 79, 78, 53])

In [28]:
a.reshape(5,6)

array([[45, 35, 59,  8, 22, 77],
       [12, 87, 79, 56, 97, 27],
       [44, 99, 69, 93, 99, 99],
       [70, 28, 60, 19, 69, 48],
       [90, 19, 86, 79, 78, 53]])

In [29]:
a.max()

99

In [30]:
a.min()

8

In [31]:
a.argmax()

13

In [32]:
a.argmin()

3

In [33]:
np.random.seed(100)

In [2]:
import pandas as pd

In [44]:
from numpy.random import randn

In [42]:
df = pd.DataFrame(randn(3,5),["1","2","3"],["a","b","c","d","e"])

In [43]:
df

a         b         c         d         e
1 -0.893259  1.738260 -1.179703  0.088571 -0.363776
2 -0.398300 -0.234715 -1.439737  0.432817  2.304473
3 -0.122635  0.015459  0.266016 -0.113795  1.011066

In [4]:
df2=pd.read_csv("insurance_data.csv")

In [5]:
df2.head()

policyID statecode       county  eq_site_limit  hu_site_limit  \
0    119736        FL  CLAY COUNTY       498960.0      498960.00   
1    448094        FL  CLAY COUNTY      1322376.3     1322376.30   
2    206893        FL  CLAY COUNTY       190724.4      190724.40   
3    333743        FL  CLAY COUNTY            0.0       79520.76   
4    172534        FL  CLAY COUNTY            0.0      254281.50   

   fl_site_limit  fr_site_limit    tiv_2011    tiv_2012  eq_site_deductible  \
0       498960.0       498960.0   498960.00   792148.90                 0.0   
1      1322376.3      1322376.3  1322376.30  1438163.57                 0.0   
2       190724.4       190724.4   190724.40   192476.78                 0.0   
3            0.0            0.0    79520.76    86854.48                 0.0   
4            0.0       254281.5   254281.50   246144.49                 0.0   

   hu_site_deductible  fl_site_deductible  fr_site_deductible  point_latitude  \
0              9979.2                 0.0                   0       30.102261   
1                 0.0                 0.0                   0       30.063936   
2                 0.0                 0.0                   0       30.089579   
3                 0.0                 0.0                   0       30.063236   
4                 0.0                 0.0                   0       30.060614   

   point_longitude         line construction  point_granularity  
0       -81.711777  Residential      Masonry                  1  
1       -81.707664  Residential      Masonry                  3  
2       -81.700455  Residential         Wood                  1  
3       -81.707703  Residential         Wood                  3  
4       -81.702675  Residential         Wood                  1

In [8]:
df2['county']

0            CLAY COUNTY
1            CLAY COUNTY
2            CLAY COUNTY
3            CLAY COUNTY
4            CLAY COUNTY
5            CLAY COUNTY
6            CLAY COUNTY
7            CLAY COUNTY
8            CLAY COUNTY
9            CLAY COUNTY
10           CLAY COUNTY
11           CLAY COUNTY
12           CLAY COUNTY
13           CLAY COUNTY
14           CLAY COUNTY
15           CLAY COUNTY
16           CLAY COUNTY
17           CLAY COUNTY
18           CLAY COUNTY
19           CLAY COUNTY
20           CLAY COUNTY
21           CLAY COUNTY
22           CLAY COUNTY
23           CLAY COUNTY
24           CLAY COUNTY
25           CLAY COUNTY
26           CLAY COUNTY
27           CLAY COUNTY
28           CLAY COUNTY
29           CLAY COUNTY
              ...       
36604    PINELLAS COUNTY
36605    PINELLAS COUNTY
36606    PINELLAS COUNTY
36607    PINELLAS COUNTY
36608    PINELLAS COUNTY
36609    PINELLAS COUNTY
36610    PINELLAS COUNTY
36611    PINELLAS COUNTY
36612    PINELLAS COUNTY


In [10]:
df2.county

0            CLAY COUNTY
1            CLAY COUNTY
2            CLAY COUNTY
3            CLAY COUNTY
4            CLAY COUNTY
5            CLAY COUNTY
6            CLAY COUNTY
7            CLAY COUNTY
8            CLAY COUNTY
9            CLAY COUNTY
10           CLAY COUNTY
11           CLAY COUNTY
12           CLAY COUNTY
13           CLAY COUNTY
14           CLAY COUNTY
15           CLAY COUNTY
16           CLAY COUNTY
17           CLAY COUNTY
18           CLAY COUNTY
19           CLAY COUNTY
20           CLAY COUNTY
21           CLAY COUNTY
22           CLAY COUNTY
23           CLAY COUNTY
24           CLAY COUNTY
25           CLAY COUNTY
26           CLAY COUNTY
27           CLAY COUNTY
28           CLAY COUNTY
29           CLAY COUNTY
              ...       
36604    PINELLAS COUNTY
36605    PINELLAS COUNTY
36606    PINELLAS COUNTY
36607    PINELLAS COUNTY
36608    PINELLAS COUNTY
36609    PINELLAS COUNTY
36610    PINELLAS COUNTY
36611    PINELLAS COUNTY
36612    PINELLAS COUNTY
